name: 'FMTM Web Forms Publish'

on:
  push:
    branches:
      - fmtm
  workflow_dispatch:

jobs:
  publish:
    name: 'Build and publish compiled web forms package'
    runs-on: 'ubuntu-latest'
    permissions:
      pages: write # to deploy to Pages
      id-token: write # to verify the deployment origin
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - uses: 'actions/checkout@v4'

      - uses: 'volta-cli/action@v4'
        with:
          node-version: '22.12.0'
          yarn-version: '1.22.22'

      - run: 'yarn install --frozen-lockfile'
      - run: 'yarn build --force'

      - name: Upload GH Pages Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # The final bundle is named odk-web-form.js
          path: packages/web-forms/dist-web-component

      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v5

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
